# Configuração padrão do Boilerplate Backend
# Este arquivo pode ser sobrescrito por variáveis de ambiente

# Configurações do Servidor
server:
  host: "0.0.0.0"
  port: "8080"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

# Configurações do Banco de Dados
database:
  host: "localhost"
  port: "5433"
  user: "postgres"
  password: "password"
  name: "boilerplate"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

# Configurações de Logging
logging:
  level: "info"  # debug, info, warn, error
  format: "json" # json, text
  output: "stdout" # stdout, stderr, file

# Configurações de Segurança
security:
  bcrypt_cost: 12
  jwt_secret: "your-secret-key-change-in-production"
  jwt_expiration: "24h"

# Configurações de Ambiente
environment: "development" # development, testing, production 